name: alpaca-kenvandine
base: core24
adopt-info: alpaca

platforms:
  amd64:
  arm64:

confinement: strict
grade: stable
compression: lzo

contact: https://github.com/kenvandine/alpaca-snap/issues
issues: https://github.com/kenvandine/alpaca-snap/issues
website: https://github.com/kenvandine/alpaca-snap

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib
  /etc/asound.conf:
    bind-file: $SNAP/etc/asound.conf
  /usr/share/alsa/alsa.conf:
    bind-file: $SNAP/usr/share/alsa/alsa.conf

slots:
  dbus-alpaca:
    interface: dbus
    bus: session
    name: com.jeffser.Alpaca

apps:
  alpaca:
    command: usr/bin/alpaca
    common-id: com.jeffser.Alpaca
    extensions:
      - gnome
    plugs:
      - alsa
      - network
      - home
      - removable-media
    environment:
      PYTHONPATH: ${SNAP}/lib/python3.12/site-packages${PYTHON_PATH:+:$PYTHON_PATH}
      HOME: $SNAP_USER_COMMON

parts:
  alsa:
    plugin: nil
    source: https://github.com/diddledan/snapcraft-alsa.git
    override-pull: |
      cat > asound.conf <<EOF
      pcm.!default {
        type pulse
        fallback "sysdefault"
        hint {
          show on
          description "Default ALSA Output (currently PulseAudio Sound Server)"
        }
      }
      ctl.!default {
        type pulse
        fallback "sysdefault"
      }
      EOF
    override-build: |
      install -m644 -D -t $CRAFT_PART_INSTALL/etc asound.conf
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
    stage:
      - usr/lib/*/libasound*
      - usr/lib/*/libOpenCL.so.*
      - usr/lib/*/libSvtAv1Enc.so.*
      - usr/lib/*/libavcodec.so.*
      - usr/lib/*/libavutil.so.*
      - usr/lib/*/libcodec2.so.*
      - usr/lib/*/libgsm.so.*
      - usr/lib/*/libhwy.so.*
      - usr/lib/*/libjxl*
      - usr/lib/*/librav1e.so.*
      - usr/lib/*/libshine.so.*
      - usr/lib/*/libsnappy.so.*
      - usr/lib/*/libsoxr.so.*
      - usr/lib/*/libswresample.so.*
      - usr/lib/*/libvpl.so.*
      - usr/lib/*/libx264.so.*
      - usr/lib/*/libxvidcore.so.*
      - usr/lib/*/libzvbi.so.*
      - usr/lib/*/alsa-lib
      - etc/asound.conf
      - etc/alsa
      - usr/share/alsa/alsa.conf

  # Python dependencies
  python-deps:
    plugin: python
    source: .
    python-packages:
      - requests==2.31.0
      - pillow==10.3.0
      - youtube-transcript-api==0.6.2
      - html2text==2024.2.26
      - pydbus==0.6.0
      - odfpy==1.4.1
      - pyicu==2.14
      - matplotlib==3.10.0
      - openai==1.61.1
      - markitdown==0.1.1
      - openai-whisper==20240930
      - pyaudio==0.2.14
    build-packages:
      - portaudio19-dev
    prime:
      - -pyvenv.cfg

  libadwaita:
    source: https://gitlab.gnome.org/GNOME/libadwaita.git
    source-tag: '1.7.2'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Ddebug=false
      - -Dintrospection=enabled
      - -Dvapi=false
      - -Dgtk_doc=false
      - -Dtests=false
      - -Dexamples=false
    build-packages:
      - bison
      - flex
      - sassc
      - libyaml-dev
      - libzstd-dev
      - libsystemd-dev
      - gperf
      - libappstream-dev
    build-environment:
      - CFLAGS: "-Wno-redundant-decls -Wno-error=format-nonliteral"
    prime:
      - usr/lib/*/*.so*
      - usr/lib/*/girepository-1.0/*
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/patches/accent-color-Return-return-orange-as-default-color.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/style-manager-Support-Yaru-accent-colors.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/accent-color-Always-expose-and-use-yaru-accent-colors-val.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/style-Add-wartybrown-accent-support.patch

  # Alpaca app
  alpaca:
    after: [libadwaita, python-deps]
    plugin: meson
    source-type: git
    source: https://github.com/Jeffser/Alpaca.git
    source-depth: 1
    source-tag: 6.0.5
    meson-parameters:
      - --prefix=/usr
      - -Ddatadir=/snap/alpaca-kenvandine/current/usr/share
    override-pull: |
      craftctl default
      sed -i 's#Jeffser/Alpaca/wiki#kenvandine/alpaca-snap/wiki#g' $CRAFT_PART_SRC/src/window.ui
    override-build: |
      craftctl default
      sed -i '1c#!/usr/bin/env python3' $CRAFT_PART_INSTALL/usr/bin/alpaca
    parse-info:
      - usr/share/metainfo/com.jeffser.Alpaca.metainfo.xml
    organize:
      snap/alpaca-kenvandine/current: .

  deps:
    plugin: nil
    after: [alpaca]
    stage-packages:
      - libnuma1
      - libspelling-1-1
      - gir1.2-vte-3.91
      - gir1.2-spelling-1
      - libvte-2.91-gtk4-0
      - libportaudio2
      - libjack-jackd2-0
      - libsamplerate0
    prime:
      - usr/lib/*/libnuma.so.*
      - usr/lib/*/libspell*.so.*
      - usr/lib/*/libvte*.so.*
      - usr/lib/*/girepository-1.0/Vte*
      - usr/lib/*/girepository-1.0/Spell*
      - usr/lib/*/libjack*.so.*
      - usr/lib/*/libportaudio*.so.*
      - usr/lib/*/libsamplerate*.so.*
